### ISSUE TITLE
 안녕하세요 라이브러리를 써볼려하는데 이러한 에러가 떠서요

### ISSUE THREAD

**Issue by KHyun94** [yongbeam/AirCalendar#11]
Unable to start activity ComponentInfo{jso.kpl.testsibal/com.yongbeom.aircalendar.AirCalendarDatePickerActivity}: android.view.InflateException: Binary XML file line #268: Binary XML file line #268: Error inflating class com.yongbeom.aircalendar.core.DayPickerView

**Comment by empty-user77** [comment]
사용하시는 환경을 알아야 확인이 가능할것 같아요

**Comment by KHyun94** [comment]
환경이라하심은 그래들을 말하시는건가요??

**Comment by empty-user77** [comment]
@KHyun94 네 gradle 에서 target sdk 등을 알려주셔야 확인이 가능할듯해요
api level 26~29로 테스트 할때는 이상이 없어서요

**Comment by KHyun94** [comment]
아 해결했습니다. gradle이라는 제시어를 주셔서 한번 비교해봤는데 구글 마테리얼을 추가해주니 되네요 감사합니다. 잘쓰겠습니다!
