### ISSUE TITLE
Feature request - internationalisation support

### ISSUE THREAD

**Issue by adriancoman** [yongbeam/AirCalendar#5]
Would you be interested in adding a feature for the calendar to have better support for internationalisation? 
Ex: 
- Change the day for the start of the week
- Change the Accept/Reset button text
- Change the weekdays name

**Comment by adriancoman** [comment]
Working on this at the moment on a fork and wanted to know if you would be interested in a pull request after i'm done with it.

**Comment by empty-user77** [comment]
Thank you for your contribution!
