### ISSUE TITLE
how to show blocked days.

### ISSUE THREAD

**Issue by umamahacse** [yongbeam/AirCalendar#8]
Hi,
I want to show some blocked days in the calendar.how can i achieve this one,is there any already predefined method call implemented in this library.

**Comment by empty-user77** [comment]
Hi, @umamahacse 
Do you want to prevent the selection of a specific date?

```intent.setBookingDateArray ('Array Dates (format: yyyy-MM-dd');```

The above option will prevent you from selecting a specific date.
