### ISSUE TITLE
selected day text color and background color are the same issue

### ISSUE THREAD

**Issue by ghost** [yongbeam/AirCalendar#9]
<img width="1392" alt="Screenshot 2019-07-02 at 1 09 53 PM" src="https://user-images.githubusercontent.com/22056214/60484134-ee7ce480-9cca-11e9-8854-490fa996a432.png">

![Screenshot 2019-07-02 at 1 04 07 PM](https://user-images.githubusercontent.com/22056214/60484417-1fa9e480-9ccc-11e9-8544-04574ef525b0.png)

mSelectedDaysColor get color from style colorSelectedDayBackground so the selected text color and the background color became the same after selection.

**Comment by empty-user77** [comment]
fix #10
